
class LanguageCode {
    constructor(title, code) {
        this.title = title;
        this.code = code;
    }
};

const languageCodes = [
    new LanguageCode('Abkhazian', 'ab'),
    new LanguageCode('Afar', 'aa'),
    new LanguageCode('Afrikaans', 'af'),
    new LanguageCode('Akan', 'ak'),
    new LanguageCode('Albanian', 'sq'),
    new LanguageCode('Amharic', 'am'),
    new LanguageCode('Arabic', 'ar'),
    new LanguageCode('Aragonese', 'an'),
    new LanguageCode('Armenian', 'hy'),
    new LanguageCode('Assamese', 'as'),
    new LanguageCode('Avaric', 'av'),
    new LanguageCode('Avestan', 'ae'),
    new LanguageCode('Aymara', 'ay'),
    new LanguageCode('Azerbaijani', 'az'),
    new LanguageCode('Bambara', 'bm'),
    new LanguageCode('Bashkir', 'ba'),
    new LanguageCode('Basque', 'eu'),
    new LanguageCode('Belarusian', 'be'),
    new LanguageCode('Bengali (Bangla)', 'bn'),
    new LanguageCode('Bihari', 'bh'),
    new LanguageCode('Bislama', 'bi'),
    new LanguageCode('Bosnian', 'bs'),
    new LanguageCode('Breton', 'br'),
    new LanguageCode('Bulgarian', 'bg'),
    new LanguageCode('Burmese', 'my'),
    new LanguageCode('Catalan', 'ca'),
    new LanguageCode('Chamorro', 'ch'),
    new LanguageCode('Chechen', 'ce'),
    new LanguageCode('Chichewa, Chewa, Nyanja', 'ny'),
    new LanguageCode('Chinese', 'zh'),
    new LanguageCode('Chinese (Simplified)', 'zh-Hans'),
    new LanguageCode('Chinese (Traditional)', 'zh-Hant'),
    new LanguageCode('Chuvash', 'cv'),
    new LanguageCode('Cornish', 'kw'),
    new LanguageCode('Corsican', 'co'),
    new LanguageCode('Cree', 'cr'),
    new LanguageCode('Croatian', 'hr'),
    new LanguageCode('Czech', 'cs'),
    new LanguageCode('Danish', 'da'),
    new LanguageCode('Divehi, Dhivehi, Maldivian', 'dv'),
    new LanguageCode('Dutch', 'nl'),
    new LanguageCode('Dzongkha', 'dz'),
    new LanguageCode('English', 'en'),
    new LanguageCode('Esperanto', 'eo'),
    new LanguageCode('Estonian', 'et'),
    new LanguageCode('Ewe', 'ee'),
    new LanguageCode('Faroese', 'fo'),
    new LanguageCode('Fijian', 'fj'),
    new LanguageCode('Finnish', 'fi'),
    new LanguageCode('French', 'fr'),
    new LanguageCode('Fula, Fulah, Pulaar, Pular', 'ff'),
    new LanguageCode('Galician', 'gl'),
    new LanguageCode('Gaelic (Scottish)', 'gd'),
    new LanguageCode('Gaelic (Manx)', 'gv'),
    new LanguageCode('Georgian', 'ka'),
    new LanguageCode('German', 'de'),
    new LanguageCode('Greek', 'el'),
    new LanguageCode('Greenlandic', 'kl'),
    new LanguageCode('Guarani', 'gn'),
    new LanguageCode('Gujarati', 'gu'),
    new LanguageCode('Haitian Creole', 'ht'),
    new LanguageCode('Hausa', 'ha'),
    new LanguageCode('Hebrew', 'he'),
    new LanguageCode('Herero', 'hz'),
    new LanguageCode('Hindi', 'hi'),
    new LanguageCode('Hiri Motu', 'ho'),
    new LanguageCode('Hungarian', 'hu'),
    new LanguageCode('Icelandic', 'is'),
    new LanguageCode('Ido', 'io'),
    new LanguageCode('Igbo', 'ig'),
    new LanguageCode('Indonesian', 'id, in'),
    new LanguageCode('Interlingua', 'ia'),
    new LanguageCode('Interlingue', 'ie'),
    new LanguageCode('Inuktitut', 'iu'),
    new LanguageCode('Inupiak', 'ik'),
    new LanguageCode('Irish', 'ga'),
    new LanguageCode('Italian', 'it'),
    new LanguageCode('Japanese', 'ja'),
    new LanguageCode('Javanese', 'jv'),
    new LanguageCode('Kalaallisut, Greenlandic', 'kl'),
    new LanguageCode('Kannada', 'kn'),
    new LanguageCode('Kanuri', 'kr'),
    new LanguageCode('Kashmiri', 'ks'),
    new LanguageCode('Kazakh', 'kk'),
    new LanguageCode('Khmer', 'km'),
    new LanguageCode('Kikuyu', 'ki'),
    new LanguageCode('Kinyarwanda (Rwanda)', 'rw'),
    new LanguageCode('Kirundi', 'rn'),
    new LanguageCode('Kyrgyz', 'ky'),
    new LanguageCode('Komi', 'kv'),
    new LanguageCode('Kongo', 'kg'),
    new LanguageCode('Korean', 'ko'),
    new LanguageCode('Kurdish', 'ku'),
    new LanguageCode('Kwanyama', 'kj'),
    new LanguageCode('Lao', 'lo'),
    new LanguageCode('Latin', 'la'),
    new LanguageCode('Latvian (Lettish)', 'lv'),
    new LanguageCode('Limburgish ( Limburger)', 'li'),
    new LanguageCode('Lingala', 'ln'),
    new LanguageCode('Lithuanian', 'lt'),
    new LanguageCode('Luga-Katanga', 'lu'),
    new LanguageCode('Luganda, Ganda', 'lg'),
    new LanguageCode('Luxembourgish', 'lb'),
    new LanguageCode('Manx', 'gv'),
    new LanguageCode('Macedonian', 'mk'),
    new LanguageCode('Malagasy', 'mg'),
    new LanguageCode('Malay', 'ms'),
    new LanguageCode('Malayalam', 'ml'),
    new LanguageCode('Maltese', 'mt'),
    new LanguageCode('Maori', 'mi'),
    new LanguageCode('Marathi', 'mr'),
    new LanguageCode('Marshallese', 'mh'),
    new LanguageCode('Moldavian', 'mo'),
    new LanguageCode('Mongolian', 'mn'),
    new LanguageCode('Nauru', 'na'),
    new LanguageCode('Navajo', 'nv'),
    new LanguageCode('Ndonga', 'ng'),
    new LanguageCode('Northern Ndebele', 'nd'),
    new LanguageCode('Nepali', 'ne'),
    new LanguageCode('Norwegian', 'no'),
    new LanguageCode('Norwegian bokmål', 'nb'),
    new LanguageCode('Norwegian nynorsk', 'nn'),
    new LanguageCode('Nuosu', 'ii'),
    new LanguageCode('Occitan', 'oc'),
    new LanguageCode('Ojibwe', 'oj'),
    new LanguageCode('Old Church Slavonic, Old Bulgarian', 'cu'),
    new LanguageCode('Oriya', 'or'),
    new LanguageCode('Oromo (Afaan Oromo)', 'om'),
    new LanguageCode('Ossetian', 'os'),
    new LanguageCode('Pāli', 'pi'),
    new LanguageCode('Pashto, Pushto', 'ps'),
    new LanguageCode('Persian', 'fa'),
    new LanguageCode('Polish', 'pl'),
    new LanguageCode('Portuguese', 'pt'),
    new LanguageCode('Punjabi (Eastern)', 'pa'),
    new LanguageCode('Quechua', 'qu'),
    new LanguageCode('Romansh', 'rm'),
    new LanguageCode('Romanian', 'ro'),
    new LanguageCode('Russian', 'ru'),
    new LanguageCode('Sami', 'se'),
    new LanguageCode('Samoan', 'sm'),
    new LanguageCode('Sango', 'sg'),
    new LanguageCode('Sanskrit', 'sa'),
    new LanguageCode('Serbian', 'sr'),
    new LanguageCode('Serbo-Croatian', 'sh'),
    new LanguageCode('Sesotho', 'st'),
    new LanguageCode('Setswana', 'tn'),
    new LanguageCode('Shona', 'sn'),
    new LanguageCode('Sichuan Yi', 'ii'),
    new LanguageCode('Sindhi', 'sd'),
    new LanguageCode('Sinhalese', 'si'),
    new LanguageCode('Siswati', 'ss'),
    new LanguageCode('Slovak', 'sk'),
    new LanguageCode('Slovenian', 'sl'),
    new LanguageCode('Somali', 'so'),
    new LanguageCode('Southern Ndebele', 'nr'),
    new LanguageCode('Spanish', 'es'),
    new LanguageCode('Sundanese', 'su'),
    new LanguageCode('Swahili (Kiswahili)', 'sw'),
    new LanguageCode('Swati', 'ss'),
    new LanguageCode('Swedish', 'sv'),
    new LanguageCode('Tagalog', 'tl'),
    new LanguageCode('Tahitian', 'ty'),
    new LanguageCode('Tajik', 'tg'),
    new LanguageCode('Tamil', 'ta'),
    new LanguageCode('Tatar', 'tt'),
    new LanguageCode('Telugu', 'te'),
    new LanguageCode('Thai', 'th'),
    new LanguageCode('Tibetan', 'bo'),
    new LanguageCode('Tigrinya', 'ti'),
    new LanguageCode('Tonga', 'to'),
    new LanguageCode('Tsonga', 'ts'),
    new LanguageCode('Turkish', 'tr'),
    new LanguageCode('Turkmen', 'tk'),
    new LanguageCode('Twi', 'tw'),
    new LanguageCode('Uyghur', 'ug'),
    new LanguageCode('Ukrainian', 'uk'),
    new LanguageCode('Urdu', 'ur'),
    new LanguageCode('Uzbek', 'uz'),
    new LanguageCode('Venda', 've'),
    new LanguageCode('Vietnamese', 'vi'),
    new LanguageCode('Volapük', 'vo'),
    new LanguageCode('Wallon', 'wa'),
    new LanguageCode('Welsh', 'cy'),
    new LanguageCode('Wolof', 'wo'),
    new LanguageCode('Western Frisian', 'fy'),
    new LanguageCode('Xhosa', 'xh'),
    new LanguageCode('Yiddish', 'yi, ji'),
    new LanguageCode('Yoruba', 'yo'),
    new LanguageCode('Zhuang, Chuang', 'za'),
    new LanguageCode('Zulu', 'zuA')];

const LanguageCodeMapping = new Map();
for (let i = 0; i < languageCodes.length; i++) {
    LanguageCodeMapping.set(languageCodes[i].code, languageCodes[i].title);
}

export class MultiLingualData {
    constructor(defaultLanguage, value = "") {
        this.defaultLanguage = defaultLanguage;
        this.values = new Map(); //[{ code: this.defaultLanguage, value: '' }];
        this.values.set(defaultLanguage, value);
    }
};

export const defaultMultiLingualData = new MultiLingualData('fa');

export default LanguageCodeMapping;

